### PR TITLE
fix(blueprint): add function to generate parameters content

### PR DESCRIPTION
**Pull request by grozwalker**
change parameter string deppends on exampe parameter

https://github.com/dingo/api/issues/1665

### CODE REVIEW

**Comment by specialtactics** [comment]
Invalid, as explained in https://github.com/dingo/api/issues/1665#issuecomment-503977472

**Comment by specialtactics** [comment]
Approved, actually the syntax is a valid use-case.

**Comment by grozwalker** [comment]
Is the coding style good enough? Maybe my code in the request should be arranged differently?

**Comment by specialtactics** [comment]
I think it's fine :smile:

**Pull request merged**
