### PR TITLE
Add attribute support to annotations

### PR DESCRIPTION
**Pull request by stygiansabyss**
Added the ability to set attributes much like parameters are set.

https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section

```
     * @Attributes({
     *      @Attribute("title", type="string", description="The title of the issue."),
     *      @Attribute("project_id", type="string", description="The ID of the project to assign it to."),
     *      @Attribute("project_key", type="string", description="The key of the assigned project."),
     *      @Attribute("description", type="string", description="Detailed notes on what the issue should accomplish.")
     * })
```

### CODE REVIEW

**Comment by jasonlewis** [comment]
Are you able to provide tests so we can ensure the output is as we expect it?

**Comment by stygiansabyss** [comment]
I will get some added, yeah.

**Comment by jasonlewis** [comment]
Awesome, cheers mate. :+1:

**Comment by stygiansabyss** [comment]
Tests have been added sir.

**Comment by jasonlewis** [comment]
Cheers, looks good. I just read over the spec, this looks like it's basic support. I'll see how possible it is to expand upon this to properly support the spec.

**Comment by stygiansabyss** [comment]
Are you referring to its use in Response blocks?

**Comment by jasonlewis** [comment]
That and defining it on a resource then embedding it elsewhere with the resource name as the identifier.

**Pull request merged**
