### PR TITLE
Add Laravel 9 Support

### PR DESCRIPTION
**Pull request by dmason30**
@specialtactics Ran tests locally with Laravel 9 on PHP 8 Successfully.

Once this is merged and tagged, I should be able to produce a Laravel 9 PR for https://github.com/api-ecosystem-for-laravel/dingo-api ❤️

### CODE REVIEW

**Comment by christoph-kluge** [comment]
Is there anything missing before this gets merged?

**Comment by christoph-kluge** [comment]
@specialtactics could you add an update regarding this PR? 

It's the only one missing to be merged to add official laravel-9 support for dingo at https://github.com/api-ecosystem-for-laravel/dingo-api/pull/18

**Comment by devglrd** [comment]
@specialtactics Hi, is possible to merge this PR for have a full laravel 9 support of dingo-api.

Please

**Comment by specialtactics** [comment]
Hey guys, sorry for the delay - was on holidays.

**Pull request merged**
