### PR TITLE
Add Members to Parameter

### PR DESCRIPTION
**Pull request by yuters**
Add a list of choices for a parameter.

https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-uriparameters-section

Usage example:

```
@Parameter("status", default="approved", members={
    @Member(value="approved", description="All the approved resources."),
    @Member(value="declined", description="All the declined resources."),
}),
```

Signed-off-by: Martin Bastien martin.bastien@studiofrenetic.com

### CODE REVIEW

**Comment by jasonlewis** [comment]
Any chance you can add some tests for this? Also the spec looks like it asks for `enum[]` to be wrapped around the `type` when members are present. That should be possible as well with this implementation I think.

If you've not got the time I can merge this in and have a crack at the rest.

**Comment by yuters** [comment]
Done. Thanks for the feedback!

I figure you could also write the enum this way:
`@Parameter("order", type="enum[string]", members={...`
instead of a condition... I'm not sure what's best.

Let me know if everything is ok

**Comment by stygiansabyss** [comment]
Id bet if the tests were run again, this would pass and could be merged in.

**Comment by jasonlewis** [comment]
All good, thanks for this looks excellent! :smile:

**Pull request merged**
