### PR TITLE
feat: add support for Laravel 10

### PR DESCRIPTION
**Pull request by patoui**
Description
----
Ran some tests locally on Laravel 10 on PHP 8.1, no errors occurred. 🚀 

image

### CODE REVIEW

**Comment by patoui** [comment]
@christoph-kluge / @specialtactics could either of you please review this PR? 🙏🏻

**Comment by christoph-kluge** [comment]
@patoui thanks for adding L10 support. Hence I do not maintainer permissions in order to continue.

**Comment by patoui** [comment]
@specialtactics any chance you could take a look at this PR and potentially merge it? 🙏🙇

**Comment by patoui** [comment]
@hskrasek or @thilanga any chance either of you could look at this? 🙏🏻 🙇🏻

**Comment by ABouchard55** [comment]
How has this not be merged yet 😩

**Comment by specialtactics** [comment]
Merged, thanks for the wait - apologies as I've been away almost continuously since late Jan (and still am).

Tagged as v0.4.5

**Comment by patoui** [comment]
No worries, thanks for merging this @specialtactics !

**Pull request merged**
