### PR TITLE
Laravel 5.3

### PR DESCRIPTION
**Pull request by mmswiderski**
Handling of Laravel 5.3 key/value order change in Array::first with backward compatibility

### CODE REVIEW

**Comment by hskrasek** [comment]
@mmswiderski Would you by chance be able to add a test with this?

**Comment by mmswiderski** [comment]
@hskrasek sure, done.

**Comment by mmswiderski** [comment]
@hskrasek Is there anything else you need? I would like to include dingo in my current project and this issue is one of blockers :)

**Comment by mmswiderski** [comment]
@hskrasek is there a problem with this PR?

**Comment by spiritix** [comment]
Please merge, I am also waiting for this

**Comment by german-bortoli** [comment]
!Need merge please

**Comment by joearcher** [comment]
Can we get this merged please? I can't generate any docs at all on Laravel 5.3

**Comment by mcblum** [comment]
+1 a merge would be great!

**Comment by jdwit** [comment]
+1 please merge!

**Review by hskrasek — APPROVED** [review]

**Pull request merged**
